services:
  securite-applications-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:80
    environment:
      DB_SERVER: securite-applications-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - securite-applications-db
    networks:
      - securite-applications-network
    volumes:
      - ./exercices:/var/www/html/Livre-Securite-applications-web-Strategies-offensives-defensives/exercices
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  securite-applications-db:
    image: mariadb:11.4.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - securite-applications-network
    volumes:
      - securite-applications-data:/var/lib/mysql
      - ./exercices:/var/www/html/Livre-Securite-applications-web-Strategies-offensives-defensives/exercices
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  securite-applications-network:
    driver: bridge

volumes:
  securite-applications-data: